### PR TITLE
Add output formatter options, & minor tweaks

### PR DESCRIPTION
**Pull request by ChrisMBarr**
I have:
- Added a `reportFn` option _(to allow people to have their own console output preferences)_
- Added a `summaryReportFn` option for the same reason as above, and the ability to turn this off if desired
- Removed the `chalk` dependency (since `gutil` has this built in!)
- Improved the default summary output language

All tests still pass, however I'm unsure if new ones should be made for these new options.

### CODE REVIEW

**Comment by tschortsch** [comment]
Thanks for your help!

**Comment by ChrisMBarr** [comment]
No problem!  We are using this along with other validation/linting packages on our source control server, and having the ability to customize the output messages will be a huge improvement for us!

**Comment by tschortsch** [comment]
I just released v0.7.0 with the new options and bootlint v0.14.1. See https://www.npmjs.com/package/gulp-bootlint. Just one notice: I changed the parameter order of the summaryReportFn to fit the order of reportFn.

**Comment by ChrisMBarr** [comment]
Ok perfect, glad you caught that. I shall update and implement it in my app tomorrow morning!

**Pull request merged**
